/**
 * Reference layer — "CRISIS 10 DE AGOSTO", the citizen-curated Google My Maps
 * of the 10 Aug 2026 quake.
 *
 * This is a different kind of data from `reports`, and the map has to keep the
 * two visually apart. Reports are anonymous signals that entered our own
 * pipeline (ingest → categorize → geolocate → N-of-M verify → publish).
 * These pins were curated by hand from official bulletins and established
 * media, each carrying its own "Fuente:" line — so they get their own source,
 * their own square markers, and their own legend section rather than being
 * injected into the report stream as if someone had texted them in.
 *
 * The curators' own warning applies and travels with the data: this is NOT an
 * official source. Emergencies: 123.
 *
 * Data lives in `./mapa-verificado.data.ts`, regenerated by
 * `bun run map:sync` — see that script for why it's a committed snapshot.
 */

import type { Feature, FeatureCollection, Geometry } from "geojson";
import {
  MAPA_VERIFICADO_URL,
  PUNTOS_SINCRONIZADOS,
} from "./mapa-verificado.data";
import { PUNTOS_LOCALES } from "./mapa-verificado.local";

// ── Layers ────────────────────────────────────────────────────────────────
export const CAPAS_VERIFICADAS = [
  "peligro",
  "ayuda",
  "logistica",
  "vias",
] as const;
export type CapaVerificada = (typeof CAPAS_VERIFICADAS)[number];

export const CAPA_LABELS: Record<CapaVerificada, string> = {
  peligro: "Zonas de peligro",
  ayuda: "Acopio y hospitales",
  logistica: "Frentes de trabajo",
  vias: "Corredores viales",
};

/**
 * Colors mirror the source map's own four buckets. They deliberately don't
 * reuse `CATEGORY_META` — a red report dot and a red danger square mean
 * different things, and only the shape tells you which pipeline it came from.
 */
export const CAPA_META: Record<CapaVerificada, { color: string }> = {
  peligro: { color: "#dc2626" },
  ayuda: { color: "#10b981" },
  logistica: { color: "#3b82f6" },
  vias: { color: "#eab308" },
};

/** A closed corridor reads as danger, not as a corridor. */
const CERRADA_COLOR = CAPA_META.peligro.color;

/**
 * Where a pin came from. Both kinds are curated rather than reported, but they
 * don't carry the same weight: `mymaps` is a volunteer's transcription of a
 * bulletin, `oficial` is published directly by an authority (an alcaldía, the
 * Cruz Roja). The map says which, because "no es fuente oficial" is true of the
 * first and would be a lie about the second.
 */
export type OrigenVerificado = "mymaps" | "oficial";

export type PuntoVerificado = {
  id: string;
  layer: CapaVerificada;
  /** Leading emoji the curators used (⛔ 📦 🏥 🚁 …) — kept for the popup. */
  emoji: string;
  /** Full title, minus the emoji. */
  title: string;
  /** Head of the title ("HUV Cali"), short enough to label on the map. */
  short: string;
  /** Description, minus the trailing attribution. */
  body: string;
  /** The "Fuente: …" line, when the curators recorded one. */
  source: string | null;
  /** The pin is a stand-in — confirm before acting on it. */
  approx: boolean;
  /** Corridor state; null on every other layer. */
  estado: "abierta" | "cerrada" | null;
  origen: OrigenVerificado;
  geometry: Geometry;
};

/**
 * Every reference pin: the My Maps snapshot plus the hand-curated additions.
 * They're kept in separate modules so `bun run map:sync` can overwrite the
 * former without touching the latter.
 */
export const PUNTOS_VERIFICADOS: PuntoVerificado[] = [
  ...PUNTOS_SINCRONIZADOS,
  ...PUNTOS_LOCALES,
];

export { MAPA_VERIFICADO_URL };
export {
  MAPA_VERIFICADO_AVISO,
  MAPA_VERIFICADO_NOMBRE,
  MAPA_VERIFICADO_SYNC,
} from "./mapa-verificado.data";

/** Marker color for one pin — its layer's, unless a corridor is closed. */
export function puntoColor(p: PuntoVerificado): string {
  return p.estado === "cerrada" ? CERRADA_COLOR : CAPA_META[p.layer].color;
}

/**
 * Marker image id for a color. The map registers one square icon per distinct
 * color at load; features name theirs in an `icon` property.
 */
export function verificadoIconId(color: string): string {
  return `mc-vp-${color.replace("#", "")}`;
}

/** Every marker color the data actually uses. */
export function verificadoColors(): string[] {
  return [...new Set(PUNTOS_VERIFICADOS.map(puntoColor))];
}

export function capaCounts(): Record<CapaVerificada, number> {
  const counts = {} as Record<CapaVerificada, number>;
  for (const capa of CAPAS_VERIFICADAS) counts[capa] = 0;
  for (const p of PUNTOS_VERIFICADOS) counts[p.layer]++;
  return counts;
}

type VerifiedProps = Record<string, string>;

/**
 * Project the reference pins into GeoJSON. Everything the popup needs rides in
 * the properties as primitives — Mapbox flattens anything else to a string.
 */
export function verificadosFeatureCollection(): FeatureCollection<
  Geometry,
  VerifiedProps
> {
  const features: Feature<Geometry, VerifiedProps>[] = PUNTOS_VERIFICADOS.map(
    (p) => {
      const color = puntoColor(p);
      return {
        type: "Feature",
        id: p.id,
        geometry: p.geometry,
        properties: {
          id: p.id,
          layer: p.layer,
          emoji: p.emoji,
          title: p.title,
          short: p.short,
          body: p.body,
          source: p.source ?? "",
          approx: p.approx ? "1" : "",
          estado: p.estado ?? "",
          origen: p.origen,
          color,
          icon: verificadoIconId(color),
        },
      };
    },
  );
  return { type: "FeatureCollection", features };
}
